FROM --platform=linux/arm64 alpine:latest
RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY run/dido_sunny.jpg .
COPY run/scripts/ffmpeg-streaming.sh .

RUN chmod +x ffmpeg-streaming.sh
CMD ["./ffmpeg-streaming.sh"]